name: steampie
favicon: null
layout_spectrum: 0.75214
typography_spectrum: 0.35242123319767416
title: "Rockin' Guitar Band"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b7b7b7'
    - '#d54e92'
    - '#7c34d3'
  brandStrength: 0.125
  lightness: 0.10656528966501355
  saturation: 0.2601926187053323
  rhythmicContrast: 0.25523376394994557
purpose: []
