name: steampie
favicon: null
layout_spectrum: 0.4330079455394298
typography_spectrum: 0.35242123319767416
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8364328683819622
  lightness: 0.10656528966501355
  saturation: 0.2601926187053323
  rhythmicContrast: 0.25523376394994557
purpose: []
